import React, { useState, useEffect } from 'react';
import { ShieldAlert, Filter, Check, Eye } from 'lucide-react';
import { api, formatSnapshotUrl } from '../services/api';

export default function AlertsPage() {
  const [alerts, setAlerts] = useState([]);
  const [severityFilter, setSeverityFilter] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  const [selectedSnapshot, setSelectedSnapshot] = useState(null);
  const [loading, setLoading] = useState(false);

  const fetchAlerts = async () => {
    setLoading(true);
    try {
      const params = {};
      if (severityFilter) params.severity = severityFilter;
      if (statusFilter) params.status = statusFilter;
      const data = await api.getAlerts(params);
      setAlerts(data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, [severityFilter, statusFilter]);

  const handleAcknowledge = async (id) => {
    try {
      await api.acknowledgeAlert(id);
      fetchAlerts();
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="flex-1 p-4 flex flex-col space-y-4 overflow-y-auto">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
        <div>
          <h2 className="text-sm font-mono font-bold text-white tracking-wider flex items-center space-x-2">
            <ShieldAlert className="w-4 h-4 text-rose-400" />
            <span>SECURITY ALERTS & INCIDENT MANAGEMENT</span>
          </h2>
          <p className="text-xs text-slate-400">
            Rule violations generated by the IBVAP AI security engine.
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <div className="hidden md:flex items-center space-x-1.5 px-2 py-1 bg-cyan-950/40 border border-cyan-500/30 rounded text-[11px] font-mono text-cyan-400">
            <span>🔒 USER ISOLATED (RLS)</span>
          </div>

          <select
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            className="bg-slate-900 border border-slate-700 text-xs font-mono text-slate-300 rounded px-2.5 py-1.5 focus:outline-none focus:border-cyan-400"
          >
            <option value="">ALL SEVERITIES</option>
            <option value="CRITICAL">CRITICAL</option>
            <option value="HIGH">HIGH</option>
            <option value="MEDIUM">MEDIUM</option>
            <option value="LOW">LOW</option>
          </select>

          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="bg-slate-900 border border-slate-700 text-xs font-mono text-slate-300 rounded px-2.5 py-1.5 focus:outline-none focus:border-cyan-400"
          >
            <option value="">ALL STATUSES</option>
            <option value="NEW">NEW / ACTIVE</option>
            <option value="ACKNOWLEDGED">ACKNOWLEDGED</option>
          </select>
        </div>
      </div>

      {/* Alerts Grid */}
      <div className="space-y-3">
        {alerts.length === 0 ? (
          <div className="p-12 text-center text-slate-500 font-mono text-xs flex flex-col items-center justify-center space-y-3">
            <p>{loading ? 'Querying encrypted alert database...' : 'No alerts recorded for this account. Each user account has private, encrypted storage.'}</p>
            {!loading && (
              <button
                onClick={async () => {
                  setLoading(true);
                  await api.seedSampleUserData();
                  await fetchAlerts();
                }}
                className="px-3 py-1.5 bg-cyan-950/70 hover:bg-cyan-900/80 text-cyan-300 border border-cyan-500/40 rounded text-xs transition-all shadow-[0_0_15px_rgba(0,240,255,0.15)]"
              >
                + SIMULATE INTRUSION INCIDENT FOR THIS ACCOUNT
              </button>
            )}
          </div>
        ) : (
          alerts.map((al) => (
            <div
              key={al.alert_id}
              className="bg-[#0d1117] border border-slate-800 hover:border-slate-700 rounded p-4 flex flex-col md:flex-row items-start justify-between gap-4 transition-colors"
            >
              <div className="flex-1 space-y-2">
                <div className="flex items-center space-x-2">
                  <span className={`px-2 py-0.5 text-[10px] font-mono font-bold rounded uppercase ${
                    al.severity === 'CRITICAL' ? 'bg-rose-500/20 text-rose-400 border border-rose-500/40' :
                    al.severity === 'HIGH' ? 'bg-orange-500/20 text-orange-400 border border-orange-500/40' :
                    'bg-amber-500/20 text-amber-400 border border-amber-500/40'
                  }`}>
                    {al.severity}
                  </span>
                  <span className="text-xs font-mono font-bold text-white">
                    {al.event_type.replace('_', ' ')}
                  </span>
                  <span className="text-[11px] font-mono text-slate-500">[{al.alert_id}]</span>
                  <span className={`text-[10px] font-mono px-1.5 py-0.2 rounded ${
                    al.status === 'NEW' ? 'bg-rose-950/60 text-rose-300 border border-rose-800' : 'bg-slate-800 text-slate-400'
                  }`}>
                    {al.status}
                  </span>
                </div>

                <p className="text-xs text-slate-300">{al.description}</p>

                <div className="flex flex-wrap gap-x-4 gap-y-1 text-[11px] font-mono text-slate-400">
                  <div><span className="text-slate-500">CAMERA:</span> {al.camera_id}</div>
                  <div><span className="text-slate-500">ZONE:</span> {al.zone_name || 'N/A'}</div>
                  <div><span className="text-slate-500">OBJECT:</span> {al.object_type?.toUpperCase()} {al.track_id ? `#${al.track_id}` : ''}</div>
                  <div><span className="text-slate-500">CONFIDENCE:</span> {al.confidence}</div>
                  <div><span className="text-slate-500">TIMESTAMP:</span> {new Date(al.timestamp).toLocaleString()}</div>
                </div>
              </div>

              {/* Snapshot thumbnail and Action button */}
              <div className="flex items-center space-x-3 shrink-0">
                {al.snapshot_path && (
                  <button
                    onClick={() => setSelectedSnapshot(formatSnapshotUrl(al.snapshot_path))}
                    className="relative group w-24 h-16 rounded border border-slate-700 overflow-hidden bg-black"
                  >
                    <img
                      src={formatSnapshotUrl(al.snapshot_path)}
                      alt="Incident Snapshot"
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform"
                    />
                    <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 flex items-center justify-center transition-opacity">
                      <Eye className="w-4 h-4 text-cyan-400" />
                    </div>
                  </button>
                )}

                {al.status === 'NEW' && (
                  <button
                    onClick={() => handleAcknowledge(al.alert_id)}
                    className="flex items-center space-x-1.5 px-3 py-2 bg-slate-800 hover:bg-slate-700 text-cyan-400 text-xs font-mono rounded border border-slate-700 transition-colors"
                  >
                    <Check className="w-3.5 h-3.5" />
                    <span>ACKNOWLEDGE</span>
                  </button>
                )}
              </div>
            </div>
          ))
        )}
      </div>

      {/* Snapshot Modal */}
      {selectedSnapshot && (
        <div className="fixed inset-0 bg-black/85 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-[#0d1117] border border-cyan-500/40 rounded-lg p-4 max-w-2xl w-full">
            <div className="flex items-center justify-between mb-3 border-b border-slate-800 pb-2">
              <span className="font-mono font-bold text-white text-xs">VIOLATION SNAPSHOT EVIDENCE</span>
              <button
                onClick={() => setSelectedSnapshot(null)}
                className="text-slate-400 hover:text-white font-mono text-sm"
              >
                ✕
              </button>
            </div>
            <div className="bg-black rounded overflow-hidden flex items-center justify-center max-h-[70vh]">
              <img src={selectedSnapshot} alt="Snapshot detail" className="max-w-full max-h-[70vh] object-contain" />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
